name: Deploy to Vercel (Beta)

on:
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - beta
  push:
    branches:
      - main

jobs:
  deploy:
    # Only run if the PR was merged (not just closed)
    # if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'beta' && github.event.pull_request.head.ref == 'main'
    runs-on: ubuntu-latest
    
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Generate Prisma client
        run: npx prisma generate
        
      - name: Deploy to Vercel
        run: |
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
